version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: job-agency-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: job-agency
    volumes:
      - mongodb_data:/data/db
    networks:
      - job-agency-network

networks:
  job-agency-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
